project5-voting/project5-voting/Models/Ad.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project5_voting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public long id { get; set; }
        public string nationalId { get; set; }
        public string data { get; set; }
        public string listId { get; set; }
        public string partyName { get; set; }
        public string electionArea { get; set; }
        public string description { get; set; }
        public string URL { get; set; }
        public string status { get; set; }
    }
}

project5-voting/project5-voting/Controllers/AdsController.cs
using project5_voting.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace project5_voting.Controllers
{
    public class AdsController : Controller
    {
           
        private ElectionsEntities2 db = new ElectionsEntities2();
        private readonly string PayPalBaseUrl = "https://api.sandbox.paypal.com/";
        private readonly string ClientId = "ARPUvF-CVZ4yA8o3ZTmyxU_9aw2AJZYjW8pDJ09OXyPNPy9aZYNPxSdc-ZCBpF8YT64dnwh6EEfXEZo5";
        private readonly string Secret = "EGQ1yUiAMYaL706LnAuZ7Iw6iP9EY055w16japE4OxnTvCbZ8INxSm7pq5TN1twjyirDkRSZo-GqA4-T";
        // GET: Ads
        public ActionResult advertisementAdmin()
        {
            return View(db.Ads.ToList());
        }

        // GET: Ads/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ad ad = db.Ads.Find(id);
            if (ad == null)
            {
                return HttpNotFound();
            }
            return View(ad);
        }

        // GET: Ads/Create
        public ActionResult addAdvertisement()
        {
            return View();
        }

        // POST: Ads/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> addAdvertisement([Bind(Include = "id,nationalId,data,listId,partyName,electionArea,description,status")] Ad ad, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(upload.FileName);

                    var path = Path.Combine(Server.MapPath("~/Images/"), fileName);


                    if (!Directory.Exists(Server.MapPath("~/Images/")))
                    {
                        Directory.CreateDirectory(Server.MapPath("~/Images/"));
                    }


                    upload.SaveAs(path);
                    ad.URL = fileName;
                }
                db.Ads.Add(ad);
                db.SaveChanges();

            }
            try
            {
                var accessToken = await GetAccessToken1();

                var paymentPayload = new
                {
                    intent = "sale",
                    payer = new
                    {
                        payment_method = "paypal"
                    },
                    transactions = new[]
                    {
                        new
                        {
                            amount = new
                            {
                                total = "1.1",
                                currency = "USD"
                            },
                            description = "Payment description"
                        }
                    },
                    redirect_urls = new
                    {
                        return_url = "https://example.com/returnUrl",
                        cancel_url = "https://example.com/cancelUrl"
                    }
                };

                var paymentJson = Newtonsoft.Json.JsonConvert.SerializeObject(paymentPayload);

                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(PayPalBaseUrl);
                    client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
                    client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

                    var content = new StringContent(paymentJson, Encoding.UTF8, "application/json");

                    var response = await client.PostAsync("/v1/payments/payment", content);

                    if (response.IsSuccessStatusCode)
                    {
                        var responseContent = await response.Content.ReadAsStringAsync();
                        var responseObject = Newtonsoft.Json.JsonConvert.DeserializeObject<dynamic>(responseContent);

                        string approvalUrl = null;
                        var linksArray = responseObject.links as Newtonsoft.Json.Linq.JArray;
                        if (linksArray != null)
                        {
                            var approvalLink = linksArray.FirstOrDefault(l => (string)l["rel"] == "approval_url");
                            if (approvalLink != null)
                            {
                                approvalUrl = approvalLink["href"].ToString();
                            }
                        }

                        if (!string.IsNullOrEmpty(approvalUrl))
                        {
                            return Redirect(approvalUrl);
                        }
                        else
                        {
                            ViewBag.ErrorMessage = "Approval URL not found in PayPal response.";
                            return View("Error");
                        }
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Failed to initiate PayPal payment: " + response.ReasonPhrase;
                        return View("Error");
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "An error occurred: " + ex.Message;
                return View("Error");
            }
        }

        public ActionResult Publish(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ad ad = db.Ads.Find(id);
            if (ad == null)
            {
                return HttpNotFound();
            }

            // Update the status of the ad to published
            ad.status = "Published";
            db.Entry(ad).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Publish", new { id = ad.id });
        }

        public ActionResult Publishs()
        {
            // إرجاع جميع الإعلانات من قاعدة البيانات
            var ads = db.Ads.ToList();
            return View(ads);
        }


        // GET: Ads/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ad ad = db.Ads.Find(id);
            if (ad == null)
            {
                return HttpNotFound();
            }
            return View(ad);
        }

        // POST: Ads/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,nationalId,data,listId,partyName,electionArea,description,URL,status")] Ad ad, HttpPostedFileBase upload)
        {
            if (upload != null && upload.ContentLength > 0)
            {
                var fileName = Path.GetFileName(upload.FileName);

                var path = Path.Combine(Server.MapPath("~/Images/"), fileName);


                if (!Directory.Exists(Server.MapPath("~/Images/")))
                {
                    Directory.CreateDirectory(Server.MapPath("~/Images/"));
                }


                upload.SaveAs(path);
                ad.URL = fileName;
            }
            if (ModelState.IsValid)
            {
                db.Entry(ad).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("advertisementAdmin");
            }
            return View(ad);
        }

        // GET: Ads/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ad ad = db.Ads.Find(id);
            if (ad == null)
            {
                return HttpNotFound();
            }
            return View(ad);
        }

        // POST: Ads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Ad ad = db.Ads.Find(id);
            db.Ads.Remove(ad);
            db.SaveChanges();
            return RedirectToAction("advertisementAdmin");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }








        //paymnt


        public async Task<ActionResult> Checkout()
        {
            try
            {
                var accessToken = await GetAccessToken();

                var paymentPayload = new
                {
                    intent = "sale",
                    payer = new
                    {
                        payment_method = "paypal"
                    },
                    transactions = new[]
                    {
                        new
                        {
                            amount = new
                            {
                                total = "130.1",
                                currency = "USD"
                            },
                            description = "Payment description"
                        }

project5-voting/project5-voting/Views/Ads/Delete.cshtml
@model project5_voting.Models.Ad

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ad</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nationalId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nationalId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.data)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.listId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.listId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.partyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.partyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.electionArea)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.electionArea)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "advertisementAdmin")
        </div>
    }
</div>

project5-voting/project5-voting/Views/Ads/Details.cshtml
@model project5_voting.Models.Ad

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Ad</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nationalId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nationalId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.data)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.listId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.listId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.partyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.partyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.electionArea)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.electionArea)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URL)
        </dt>

        <dd>
            <img src="~/Images/@Model.URL" alt="No Image" width="100" height="100" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "advertisementAdmin")
</p>

project5-voting/project5-voting/Views/Ads/Publish.cshtml
@model project5_voting.Models.Ad

@{
    ViewBag.Title = "Publish";
}

<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="~/Images/@Model.URL" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">@Model.data</h5>
        <p class="card-title">@Model.partyName</p>
        <p class="card-text">@Model.description</p>
        <p class="card-text"><small class="text-muted">@Model.electionArea</small></p>
    </div>
</div>

project5-voting/project5-voting/Views/Ads/Publishs.cshtml
@{
    ViewBag.Title = "Publishs";
}

<h2>Publishs</h2>
@foreach (var ad in Model)
{
    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="~/Images/@ad.URL" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">@ad.data</h5>
            <p class="card-title">@ad.partyName</p>
            <p class="card-text">@ad.description</p>
            <p class="card-text"><small class="text-muted">@ad.electionArea</small></p>
            <p class="card-text"><strong>Status:</strong> @ad.status</p>
        </div>
    </div>
}

project5-voting/project5-voting/Views/Ads/addAdvertisement.cshtml
@model project5_voting.Models.Ad

@{
    ViewBag.Title = "addAdvertisement";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>Create</h2>


@using (Html.BeginForm("addAdvertisement", "Ads", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Ad</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nationalId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nationalId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nationalId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.listId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.listId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.listId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.partyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.partyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.partyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.electionArea, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.electionArea, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.electionArea, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("URL", htmlAttributes: new { @class = "" })
            <div class="col-md-10">
                <input type="file" name="upload" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Pay with PayPal</button>



    </div>
}

project5-voting/project5-voting/Views/Ads/advertisementAdmin.cshtml
@model IEnumerable<project5_voting.Models.Ad>

@{
    ViewBag.Title = "advertisementAdmin";
}

<h2>Index</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nationalId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.data)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.listId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.partyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.electionArea)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.URL)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.status)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nationalId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.data)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.listId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.partyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.electionArea)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                <img src="~/Images/@item.URL" alt="No Image" width="100" height="100" />
            </td>

            <td>@Html.DisplayFor(modelItem => item.status)</td>
            <td>
                @Html.ActionLink("رؤية التفاصيل ", "Details", new { id = item.id }) |
                @Html.ActionLink("حذف", "Delete", new { id = item.id }) |
            </td>


            <td>
                @if (item.status != "Published")
                {
                    @Html.ActionLink("Publish", "Publish", new { id = item.id })
                }
            </td> |


        </tr>
    }

</table>